### PR TITLE
Fix support for test explorer

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Implements the workaround proposed [here](https://github.com/fsprojects/Paket/issues/516#issuecomment-124248402) so that test explorer can recognize the unit tests

### CODE REVIEW

**Comment by isaacabraham** [comment]
Ooops! I thought this was MBrace.Azure! I didn't even realise I had permissions to accept PRs for this project - apologies!!

**Comment by eiriktsarpalis** [comment]
Strange, I seem to have admin powers here myself. Must be because I'm maintaining another project in fsprojects. Is this on purpose?

**Comment by daniel-chambers** [comment]
I think @isaacabraham has admin access because he's in the AzureTeam group from fsprojects. Not sure why you have admin access @eiriktsarpalis... are you in the Owners group from fsprojects? I can't tell; I don't think I have the rights to see who is in the group.

Was there supposed to be a packages.config file committed with this? I just did a build and Paket hasn't created one automatically... maybe it only creates it when you add the package, not when restoring the packages?

**Comment by isaacabraham** [comment]
There shouldn't be a packages.config with paket, ever - that's a nuget artifact. You should just have a paket.dependencies and packet.lock file in the repo (plus normally a paket.bootstrapper.exe), and alongside every project a paket.references file.

**Comment by daniel-chambers** [comment]
The issue referenced in the OP of this PR says a packages.config should be
created by paket as a requirement to get the vs test runner working. Or am
I missing something...?

**Comment by isaacabraham** [comment]
The VS Test Runner extension expects to find the test runner for XUnit in a *versioned* package folder. Paket deliberately avoids this - all packages go into simply named folders e.g. ```packages/FSharp.Core``` rather than ```packages\FSharp.Core.4.0.0.0``` etc.., but it's required for the VS Test Runner. So the workaround in Paket is to explicitly set the ```version in path``` flag in the dependencies file to true, which instructs Paket to put the version number back in the folder path. Then the test runner works.

**Comment by isaacabraham** [comment]
It does look like some other packages in the lock file have been updated though at the same time of this PR - @eiriktsarpalis was there a reason for that?

**Comment by isaacabraham** [comment]
@daniel-chambers hmmm - seems reading through the last parts of that issue it's talking about a ```packages.config``` file - you're right. I've never seen that though - as far as I'm aware, you just need the folder with a version in it and then it should work.

**Comment by eiriktsarpalis** [comment]
You're right, `packages.config` is required for this to work. I'll follow up with a PR that adds it.

**Pull request merged**
